"""Agent state definition for LangGraph.

This module defines the typed state that flows through the LangGraph agent,
following best practices for minimal, explicit state management.
"""

from typing import Annotated, Any, TypedDict

from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """State for the multimodal AI agent.

    This state is passed through each node in the LangGraph workflow.
    Following best practices, we keep the state minimal and typed.

    Attributes:
        messages: The conversation history (using LangGraph's message accumulator).
        job_id: The ID of the current processing job.
        image_path: Path to the image in MinIO storage.
        image_data: Raw image bytes (loaded from storage).
        image_analysis: Analysis result from the vision model.
        reasoning: Reasoning/planning result from the reasoning model.
        generated_code: Python code generated by the code model.
        execution_result: Result from code execution (Phase 3).
        error: Any error that occurred during processing.
        current_step: The current step in the processing pipeline.
    """

    # Message history with LangGraph's built-in accumulator
    messages: Annotated[list[Any], add_messages]

    # Job context
    job_id: str
    user_id: str

    # Image data
    image_path: str
    image_data: bytes | None
    image_mime_type: str

    # Processing results
    image_analysis: str | None
    reasoning: str | None
    generated_code: str | None
    execution_result: str | None

    # Status tracking
    error: str | None
    current_step: str


class AgentConfig(TypedDict, total=False):
    """Configuration for the agent.

    Attributes:
        temperature: Temperature for LLM generation.
        max_tokens: Maximum tokens to generate.
        timeout: Timeout for LLM requests.
    """

    temperature: float
    max_tokens: int
    timeout: float
